-- DML COMMANDS: INSERT , DELETE , UPDATE

use pfs6;
-- create table EMPLOYEES(
-- EMPID char(5) primary key,
-- FIRSTNAME VARCHAR(50),
-- LASTNAME VARCHAR(30),
-- AGE INT,
-- DOJ DATE,
-- ADDRESS TINYTEXT,
-- DEPT VARCHAR(20));

-- INSERT IS USED TO INSERT RECORDS INTO OUR TABLE IT IS A DML COMMAND
-- SYNTAX: INSERT INTO TABLE-NAME (COULMN NAMES) VALUES ()

-- INSERT INTO EMPLOYEES (EMPID,FIRSTNAME,LASTNAME,AGE,DOJ,ADDRESS,DEPT) 
-- VALUES 
-- ('E0002','SUNNY','LEONE','35','2000-03-20','MUMBAI','SOCIALSERVICE'),
-- ('E0003','SAMPRNESH','BABU','40','1995-03-20','ANDHRAPRADESH','SOCIALSERVICE');

-- INSERT INTO EMPLOYEES
-- VALUES
-- ('E0005','SAI','KIRAN','24','2002-03-20','VIZAG','TRAINING'),
-- ('E0006','SAI','VARDHAN','32','2002-03-20','BNG','ADMIN');

-- INSERT INTO EMPLOYEES (DOJ,DEPT,ADDRESS,EMPID,FIRSTNAME,LASTNAME,AGE) -- ANOTHER APPROACH TO INSERT IN UNORDERED MANNER 
-- VALUES
-- ('2000-07-27','SALES','DELHI','E0007','BALU','SUBBU','40');

-- INSERT INTO EMPLOYEES(EMPID,FIRSTNAME,AGE,ADDRESS,DEPT) WHEN YOU WANT TO FILL ONLY SECIFIED COLUMNS NOT ALL 
-- VALUES
-- ('E0008','HARI',17,'NOIDA','HR');


-- INSERT INTO EMPLOYEES(EMPID,LASTNAME,DOJ,DEPT)  VALUES('E0009','BABU','2026-03-03','IT'); WHEN YOU WANT TO FILL ONLY SECIFIED COLUMNS NOT ALL 


-- UPDATE IT IS USED MODIFY EXISTING VALUES IN THE TABLE BUT CANNOT MODIFY IT'S STRUCTURE
-- SYNTAX: UPDATE TABLE-NAME SET COLUMN-NAME = VALUE WHERE CONDITION;

-- UPDATE EMPLOYEES SET FIRSTNAME='KATRINA' WHERE EMPID='E0002'; -- UPDATED SUNNY'S FIRST NAME TO KATRINA BASED ON EMPLOYEE ID 
-- SELECT * FROM EMPLOYEES WHERE EMPID='E0002';

-- UPDATE EMPLOYEES SET FIRSTNAME='MAHESH' WHERE LASTNAME='BABU';

-- UPDATE EMPLOYEES SET AGE=50 WHERE AGE IS NULL; -- TO UPDATE A NULL VALUE WE HAVE TO USE IS

-- UPDATE EMPLOYEES SET LASTNAME='KRISHNA' WHERE FIRSTNAME ='HARI';
-- UPDATE EMPLOYEES SET DOJ='2026-09-05' WHERE EMPID='E0003';
-- UPDATE EMPLOYEES SET ADDRESS='KOLKATHA' WHERE DEPT='IT';


-- DELETE: DELETES THE RECORDS BASED ON SOME CONDITION
-- SYNTAX: DELETE FROM TABLE-NAME WHERE SOME-CONDITION


-- DELETE FROM EMPLOYEES WHERE EMPID='E0009';
-- DELETE FROM EMPLOYEES WHERE FIRSTNAME='SAI';

-- TRUNCATE: TRUANCATE WILL DELETE ALL RECORDS IN A TABLE
-- SYNTAX: TRUNCATE TABLE TABLE-NAME;

-- TRUNCATE TABLE EMPLOYEES;
-- SELECT * FROM EMPLOYEES;
-- DESC EMPLOYEES;

-- DROP TABLE EMPLOYEES;
-- DESC EMPLOYEES;


-- DROP: REMOVES THE TABLE/OBJECT , INCLDING TABLE'S STRUCTURE AND DATA , PREFORMANCE IS SLOW DUE TO FULL REMOVAL
-- DELETE: REMOVES SPECIFIC ROWS FROM TABLE, DELETE'S A ROW BASED ON CONDITION, BUT KEEPS TABLE'S STRUCTURE, PERFORMANCE IS SLOW DUE TO REMOVES ROW-BY-ROW
-- TRUNCATE: REMOVES ALL ROWS BUT KEEPS TABLE STRUCTURE, TABLE'S STRUCTURE WILL BE INTACT , PERFORMANCE IS FAST BECAUSE IT REMOVES ALL ROWS 

-- CREATE TABLE employees (
--    emp_id INT PRIMARY KEY,
--    emp_name VARCHAR(100),
--    department VARCHAR(50),
--    job_role VARCHAR(50),
--    salary DECIMAL(10,2),
--    joining_date DATE,
--    city VARCHAR(50)
--  );


-- INSERT INTO employees
-- (emp_id, emp_name, department, job_role, salary, joining_date, city)
-- VALUES
-- (101, 'Ravi Kumar', 'IT', 'Developer', 45000, '2023-01-15', 'Vizag'),
-- (102, 'Priya Sharma', 'HR', 'HR Manager', 55000, '2022-06-20', 'Hyderabad'),
-- (103, 'Kiran Reddy', 'IT', 'Tester', 40000, '2023-03-10', 'Vizag'),
-- (104, 'Sneha Rao', 'Finance', 'Accountant', 48000, '2021-11-25', 'Chennai'),
-- (105, 'Arun Kumar', 'IT', 'Developer', 60000, '2020-08-18', 'Bangalore'),
-- (106, 'Divya Reddy', 'HR', 'Recruiter', 35000, '2024-01-05', 'Vizag'),
-- (107, 'Suresh Babu', 'Sales', 'Executive', 42000, '2022-09-12', 'Hyderabad'),
-- (108, 'Anjali Devi', 'IT', 'Developer', 70000, '2019-05-30', 'Chennai'),
-- (109, 'Mahesh Kumar', 'Sales', 'Manager', 65000, '2020-02-14', 'Bangalore'),
-- (110, 'Lakshmi Rao', 'Finance', 'Analyst', 52000, '2023-07-22', 'Hyderabad');


-- alter table employees add email varchar(100);
-- alter table employees add phone varchar(15);
-- alter table employees change city city varchar(100);
-- alter table employees change job_role designation varchar(50);
-- alter table employees drop phone;

-- update employees set salary=50000 where emp_name='Ravi_Kumar';
-- update employees set salary=salary+salary*0.1 where department='IT';
-- update employees set city='Hyderabad' where emp_name='Divya Reddy';

select * from employees;
